/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        DoublyLinkedList lilist = new DoublyLinkedList();
        lilist.insert(1);
        lilist.insert(2);
        lilist.insert(3);
        lilist.insert(4);
        lilist.insert(5);
        System.out.println(lilist.listToString());
    }
}
